var myWords = [ { word: 'will', size: 57 },
  { word: 'have', size: 51 },
  { word: 'be', size: 27 },
  { word: 'can', size: 11 },
  { word: 'down', size: 9 },
  { word: 'do', size: 9 },
  { word: 'work', size: 9 },
  { word: 'people', size: 9 },
  { word: 'want', size: 8 },
  { word: 'out', size: 8 },
  { word: 'home', size: 7 },
  { word: 'create', size: 7 },
  { word: 'help', size: 7 },
  { word: 'even', size: 6 },
  { word: 'tax', size: 6 },
  { word: 'believe', size: 6 },
  { word: 'keep', size: 6 },
  { word: 'state', size: 6 },
  { word: 'get', size: 6 },
  { word: 'make', size: 6 } ] ;
