var myWords = [ { word: 'will', size: 82 },
  { word: 'have', size: 46 },
  { word: 'be', size: 28 },
  { word: 'can', size: 26 },
  { word: 'know', size: 22 },
  { word: 'people', size: 17 },
  { word: 'plan', size: 16 },
  { word: 'do', size: 15 },
  { word: 'care', size: 13 },
  { word: 'make', size: 11 },
  { word: 'cost', size: 10 },
  { word: 'budget', size: 10 },
  { word: 'out', size: 10 },
  { word: 'tax', size: 10 },
  { word: 'put', size: 9 },
  { word: 'even', size: 9 },
  { word: 'time', size: 9 },
  { word: 'up', size: 8 },
  { word: 'back', size: 8 },
  { word: 'take', size: 8 } ] ;
